---
title: "Module 4 Challenges"
output: html_document
---

v1 <- c(1, 2, 3, 4)
v2 <- c(6 ,7 ,8 ,9)
m1 <- rbind(v1, v2)
m1

m2 <- cbind(v1, v2)
m2

a <- array( data = 1:90, dim = c(5, 6 ,3))
a

##Module 4 Challenge 1##
##I'm having trouble with actually extracting the character data as opposed to only their position in the array.

x <- "Stately, plump Buck Mulligan came from the stairhead, bearing a bowl of lather on which a mirror and a razor lay crossed."
x2 <- ((gsub("[[:punct:]]"," ", x)))
xspt <- c(unlist(strsplit(x2, " ")))

extract <- xspt[seq(from=3, to=22, by=3)]
extract

##Module 4 Challenge 2##
m <- matrix(data = 1:80, nrow = 8, ncol = 10, byrow = FALSE)
m
x <- m[,2]
x <- m[,3]
x <- m[,6]
x <- m[6,]
x <- m[8,]
x <- m[2,2]
x <- m[6,9]

##Module 4 Challenge 3##
a <- array(data = 1:400, dim=c(1,2,3,4),)
a[1, 1, 1, 2]
a[2, 3, 2, ]
a[1:5, 1:5, 3, 3]

##Module 4 Challenge 4##
s <- c("this", "is", "a", "vector", "of", "strings")
m <- matrix(data = 1:40, nrow = 5, ncol = 8)  # this is a matrix
b <- FALSE
l <- list(s, m, b)
l
str(l)

##Module 4 Challenge 5##

#a <-c("Primates")
#b <- c("Haplorhini", "Strepsirhini")
#c <- c("Anthropoidea", "Tarsioidea", "Lorisoidea", "Lemuroidea")
#d <-c("Platyrrhini
#","Catarrhini", "Tarsiidae
#", "Lorisidae", "Galagidae", "Cheirogaleidae
#", "Lepilemuridae","Indriidae","Lemuridae", "Daubentoniidae")
#e <- c("Cebidae", "Atelidae", "Pitheciidae", "Cercopithecidae", "Hylobatidae", "Hominidae")
#l <- list(a,b,c,d,e)
#l


platyrrhini <- c("cebidae", "atelidae", "pitheciidae")
catarrhini <- c("cercopithecidae", "hylobatidae", "hominidae")
tarsioidea <- c("tarsiidae")

names(anthropoidea) <- c("anthropoidea")
names(platyrrhini) <- c("platyrrhini")
names(catarrhini) <- c("catarrhini")
names(haplorhini) <- c("haplorhini")
names(tarsioidea) <- c("tarsioidea")
names(lorisoidea) <- c("lorisoidea")
names(lemuroidea) <- c("lemuroidea")

anthropoidea <- list( platyrrhini, catarrhini)
haplorhini <- list(anthropoidea, tarsioidea)

lorisoidea <- c("lorisidae", "galagidae")
lemuroidea <- c("Cheirogaleidae
", "Lepilemuridae
", "Indriidae", "Lemuridae", "Daubentoniidae")

strepsirhini <- list(lorisoidea, lemuroidea)
names(strepsirhini) <- c("strepsirhini")
primates <- list(strepsirhini, haplorhini)




names(primates) <- c("primates")

primates

#maybe write the strepsirhini

## s

##Module 4: Last Challenge##
m <- matrix(c(3, 0, 1 ,23, 1, 2, 33, 1, 1, 42, 0, 1, 41, 0, 2),nrow = 3, ncol=5, byrow = TRUE)

data.frame(m)
as.logical(m[,2])
as.factor(m[,3])
str(m)
